### ISSUE TITLE
Use in Preference Screen

### ISSUE THREAD

**Issue by tellfa** [BelkaLab/Android-Toggle-Switch#1]
Hi, thanks for this library. how can i use this in Preference Screen ?

**Comment by llollox** [comment]
Thank you.
Unfortunately at this moment Preference Screen isn't supported.
I will check to add it in the next release! :)

**Comment by tellfa** [comment]
thanks you man <3 . please add this soon :heart:

**Comment by sbouiachref** [comment]
Hi, How I can applicate style(fonts) to textToggleRight and textToggleLeft
