### ISSUE TITLE
Unable to work with the library

### ISSUE THREAD

**Issue by tuxtux59** [BelkaLab/Android-Toggle-Switch#10]
Hi,
I tried for few hours now to work with your library :)
First problem was to set 1.1.1 instead of 1.2.0
Second problem was to modify my manifest due to conflict between your and my manifest.
And badly now the library is known by gradle but nothing works on the view :/. it only create a view(by testing with a background color".
I tried your code shown in the readme and added xmlns:custom="http://schemas.android.com/tools" on my root view but nothing appears different as a view with my backgronud color.
I'm using the latest versino of Android studio and gradle 2.1.0. 
If you have an idea to what could resolve the problem :)
Thanks by advance

**Comment by Ansty93** [comment]
Iam also getting similar problem

**Comment by llollox** [comment]
I've just fixed the version 1.2.0!
Please, try with this version of the libray and notify me if your problem remain! :)
Thank you very much.

**Comment by WesleyHunt** [comment]
Same Issue here, when using in the manifest:
 tools:replace="android:theme"
        android:theme="@style/AppTheme.ActionBar.Transparent"

**Comment by llollox** [comment]
Sorry, @WesleyHunt , 
can you better explain your problem?

**Comment by WesleyHunt** [comment]
I can't seem to replicate my problem there from way back so there is no longer an issue for me. The error is below but using the replace theme line is working without conflict. I may have actually done something wrong defining custom, defining it as follows is working fine for me making the button in XML on a test project:

 xmlns:custom="http://schemas.android.com/apk/res-auto"




**..**

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/AppTheme.ActionBar.Transparent) from AndroidManifest.xml:12:9-62
  	is also present at [us.belka:androidtoggleswitch:1.2.0] AndroidManifest.xml:15:9-40 value=(@style/AppTheme).
  	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:6:5-24:19 to override.

**adding to manifest**

tools:replace="android:theme"

**Fixes this issue and allows my custom theme**

**Comment by Smartertime** [comment]
Same issue here, btw no idea why your library would need to define the application icon and theme.
