### ISSUE TITLE
Layout width "match_parent" doesn't work

### ISSUE THREAD

**Issue by janakagamini** [BelkaLab/Android-Toggle-Switch#13]
It's not possible to get this view's width to match the parent's width. Looking at the source code I believe that this is because each toggle item has a fixed width of 64dp, or as defined by `toggleWidth`.

It would be really nice if there was some option such that the toggle item width is dynamically set to -> **(available width / number of items)**, so that this view can nicely spread out on the parent view.

**Comment by tux-world** [comment]
when i set width to zero and weight to 1, my toggle switch hidden

```
<belka.us.androidtoggleswitch.widgets.ToggleSwitch
                    android:id="@+id/convert_type"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:layout_marginTop="10dp"
                    android:layout_weight="1"/>
```
