### ISSUE TITLE
"cornerRadius" has already been defined

### ISSUE THREAD

**Issue by veersamrat** [BelkaLab/Android-Toggle-Switch#17]
Earlier i use to use 1.1.1 version but now when i switch to 1.2.0 it's getting conflict with other library values.xml like

' Attribute "cornerRadius" has already been defined'

can you sort it out ?

**Comment by FRizzonelli** [comment]
Hi @veersamrat, 

we added the _cornerRadius_ attribute in the style, now it is configurable through the proper field.
Could you be more clear about your problem? Can you give us more information to reproduce your error?

Thank you,

Fabrizio
