### ISSUE TITLE
Right to left support

### ISSUE THREAD

**Issue by mathroule** [BelkaLab/Android-Toggle-Switch#18]
Hi, thanks for your lib!

There is a little issue when using the library in Arabic, the items are correctly inversed but not in a proper way.

_English_
![english](https://cloud.githubusercontent.com/assets/4117425/19438356/ca9afb6c-9479-11e6-9a33-eea71af87028.png)

_Arabic_
![arabic](https://cloud.githubusercontent.com/assets/4117425/19438355/ca98d580-9479-11e6-8199-e875429e6f19.png)

**Comment by sbouiachref** [comment]
Hi, How I can applicate style(fonts) to textToggleRight and textToggleLeft

**Comment by MahdiPishguy** [comment]
could you resolve this problem?

**Comment by MahdiPishguy** [comment]
@Juleship @mathroule could you resolve this problem?

**Comment by llollox** [comment]
@MahdiPishguy I've added this functionality in my new fork of the library.
I've tested it setting the phone's language in arabic.
Let me know if this solve your issue.

Please, check it out at https://github.com/llollox/Android-Toggle-Switch

**Comment by MahdiPishguy** [comment]
@llollox thank you. Please let us to check. Thanks in advance

**Comment by MahdiPishguy** [comment]
@llollox there are many useful feature on your repository man!! very good, specialy `match_parent`

**Comment by llollox** [comment]
@MahdiPishguy thank you very much! :)
