### ISSUE TITLE
Could not find us.belka:androidtoggleswitch:1.2.1

### ISSUE THREAD

**Issue by mathroule** [BelkaLab/Android-Toggle-Switch#19]
Hi

The version 1.2.0 is available on [https://jcenter.bintray.com/us/belka/androidtoggleswitch/1.2.0/](jcenter) but not the version 1.2.1.

**Comment by AreJay-Smith** [comment]
Same issue here.

**Comment by FRizzonelli** [comment]
Fixed

**Comment by mathroule** [comment]
It's working now, thanks!
