### ISSUE TITLE
Images instead text 

### ISSUE THREAD

**Issue by draskosaric** [BelkaLab/Android-Toggle-Switch#2]
Hi, great library! Is there a way  to put images instead labels in this toggle switch?

**Comment by llollox** [comment]
Thank you very much!!
Unfortunately it isn't supported right now.
Don't worry! I will add this feature very soon! :)

**Comment by sbouiachref** [comment]
sds

**Comment by sbouiachref** [comment]
Hi, How I can applicate style(fonts) to Textview

**Comment by llollox** [comment]
@draskosaric I've added this functionality in my new fork of the library.

You can now set your custom view for each button.
There are a few examples into the sample project.
Let me know if it solve your issue.

Please, check it out at https://github.com/llollox/Android-Toggle-Switch

**Comment by draskosaric** [comment]
Beautiful. Thanks!
