### ISSUE TITLE
Text in All Caps?

### ISSUE THREAD

**Issue by DannyJi** [BelkaLab/Android-Toggle-Switch#22]
Is there any way to set the text of switch to match the text I supply in either the XML or Java approach?  The text is set to all caps which is hard to read and against our companies style guidelines. 

In item_widget_toggle_switch.xml 

the TextView is forced to `android:textAllCaps="true" />`

**Comment by DannyJi** [comment]
@FRizzonelli any update on allowing us to control the capitalization of the text in the switch?

**Comment by FRizzonelli** [comment]
Fixed in release 1.2.2 :)

**Comment by DannyJi** [comment]
That was fast.  Thank you!
