### ISSUE TITLE
How to use 3 different colors?

### ISSUE THREAD

**Issue by vvbhandare** [BelkaLab/Android-Toggle-Switch#27]
In belka.us.androidtoggleswitch.widgets.ToggleSwitch, I have 3 buttons/labels. I want to set 3 different colors. How can I achieve this?

**Comment by sbouiachref** [comment]
Hi, How I can applicate style(fonts) to textToggleRight and textToggleLeft

**Comment by kcywek** [comment]
+1

**Comment by MahdiPishguy** [comment]
+1

**Comment by llollox** [comment]
@vvbhandare, @kcywek, @MahdiPishguy I've added this functionality in my new fork of the library.
Into the documentation there is a sample that create 3 buttons with different colors.

Please, check it out at https://github.com/llollox/Android-Toggle-Switch

**Comment by MahdiPishguy** [comment]
@llollox thank you very much
