### ISSUE TITLE
layout_width="match_parent" doesn't expand view

### ISSUE THREAD

**Issue by sikrinick** [BelkaLab/Android-Toggle-Switch#31]
layout_width="match_parent" doesn't expand view
Is it possible to add support for expanding view's width if there is free space on its sides?

**Comment by llollox** [comment]
This is not trivial since the component's width is the sum of the width of each button.
In this moment the container doesn't care about its parent's width.
That's why is possible to set the button's width.

I try to figure out your problem on the new version of the library.

**Comment by llollox** [comment]
@sikrinick I've added this functionality in my new fork of the library.
Now, setting `layout_width="match_parent"` or `layout_height="match_parent"` the buttons take all the parent's space.

Please, check it out at https://github.com/llollox/Android-Toggle-Switch

**Comment by PaolinoAngeletti** [comment]
i've tried this new library (https://github.com/llollox/Android-Toggle-Switch) but i'm receiving this error:
NoSuchMEthodException : android.widget.LinearLayout.setElevation at BaseToggleSwitch.kt.272..
please help me, the library is helpful, but this error ...

**Comment by llollox** [comment]
Which Android version are you using?

**Comment by PaolinoAngeletti** [comment]
The problem is received on an Android 4.4.4. On This version, i know that Elevation is not supported, but this problem have to be resolved on this version, too.
You have suggestions or i have to correct the source code with a try-catch statement ?
