### ISSUE TITLE
Border Line

### ISSUE THREAD

**Issue by aravindnaidu09** [BelkaLab/Android-Toggle-Switch#32]
How to have a border line for the switch with different colors.

**Comment by llollox** [comment]
You mean how to set different border colors for active and inactive bottoms?

**Comment by aravindnaidu09** [comment]
yes

**Comment by llollox** [comment]
Ok, thank you for your suggestion. I try to add it in the next version.

**Comment by llollox** [comment]
@aravindnaidu09 I've added this functionality in my new fork of the library.

Please, check it out at https://github.com/llollox/Android-Toggle-Switch
