### ISSUE TITLE
Drawable / Icon?

### ISSUE THREAD

**Issue by rpattabi** [BelkaLab/Android-Toggle-Switch#34]
I wonder if it is possible to add a drawable to the toggle buttons. I see internally toggle button is a text view. Support for drawableLeft, drawableRight, etc would be helpful as TextView already supports these.

**Comment by llollox** [comment]
In this new version of the library you can use a custom layout for each toggle button.

https://github.com/llollox/Android-Toggle-Switch

**Comment by AlecSPB** [comment]
llollox your code is broken!
