### ISSUE TITLE
setToggleWidth

### ISSUE THREAD

**Issue by stern0m1** [BelkaLab/Android-Toggle-Switch#42]
setToggleWidth is not working by me.
Trying to set the width at runtime but its having no effect.

`ToggleSwitch switchRemote = (ToggleSwitch)findViewById(R.id.switchRemote);`
`switchRemote.setToggleWidth((float)100)`

**Comment by llollox** [comment]
@stern0m1 I have fixed it in my new fork of the library.
Let me know if this solves your issue.

Please, check it out at https://github.com/llollox/Android-Toggle-Switch
