### ISSUE TITLE
Is it possible to have a ToggleSwitch without a selection to start with?

### ISSUE THREAD

**Issue by casolorz** [BelkaLab/Android-Toggle-Switch#43]
Is it possible to not have a selection made when adding a `ToggleSwitch`?

**Comment by llollox** [comment]
@casolorz  I have fixed it in my new fork of the library.
Let me know if this solves your issue.

Please, check it out at https://github.com/llollox/Android-Toggle-Switch

**Comment by casolorz** [comment]
Thanks.
