### ISSUE TITLE
Corner radius is killing this for me

### ISSUE THREAD

**Issue by jay-parapps** [BelkaLab/Android-Toggle-Switch#7]
Looks like a great codebase, however the fact that corner radius is not styleable and also private is making it useless for those that need square corners

**Comment by llollox** [comment]
Thank you very much for your suggestion.
I'm working on fixing these open issues.

I'll also add the support to corner radius on next versions.

**Comment by llollox** [comment]
In this new version (1.2.0) I've implemented the support for corner radius.

You can simply define the corner radius inside by xml, inserting the following line:
custom:cornerRadius="0dp"

This is explained also into the documentation.

Please, let me know if this solve your problem!

**Comment by jgamedev** [comment]
Cool,

For some reason when I tryed using  your component it was not showing up on screen at all, but I will give it another try this week and let you know. Thank you so much, this looks great

**Comment by llollox** [comment]
Thank you! 
Let me know if you observe any kind of problems.
