### ISSUE TITLE
how to disable toggle?

### ISSUE THREAD

**Issue by nitiwatpolo** [BelkaLab/Android-Toggle-Switch#8]
setEnabled(false) is not working?

**Comment by llollox** [comment]
Unfortunately this is not supported right now. 
I will add the support for disable toggle soon.

Thank you for your suggestion!

**Comment by yasirahmedkhan** [comment]
@GnuRant the issue is not resolved yet, I'm trying to setEnable(false) but its not working.

**Comment by joseslo** [comment]
Not supported yet? I'm trying with setEnabled(false) and doesn't work.

**Comment by llollox** [comment]
I'm working on a new version of the library with some bug fixes including this one.

**Comment by joseslo** [comment]
Nice. Its a really useful feature, I'll wait for the new version. Is there any release date estimation? no pressure haha

**Comment by llollox** [comment]
Hopefully in a couple of weeks! :)

**Comment by knightbenax** [comment]
Still waiting

**Comment by llollox** [comment]
@nitiwatpolo, @yasirahmedkhan, @joseslo, @knightbenax I've added this functionality in my new fork of the library.

You can disable the buttons just setting into the xml `android:enabled=false` or programmatically `toggleSwitch.setEnabled(false)`.
There is also an example into the samples project.

Please, check it out at https://github.com/llollox/Android-Toggle-Switch

**Comment by knightbenax** [comment]
Great!

**Comment by lambrohan** [comment]
toggleSwitch.setEnabled(false) not working!
