### ISSUE TITLE
faied to resolve 

### ISSUE THREAD

**Issue by iceberg1369** [BelkaLab/Android-Toggle-Switch#9]
I have added Android-Toggle-Switch to my app build.gradle
but once I hit sync it throws following error
faied to resolve Error:(34, 13) Failed to resolve: us.belka:androidtoggleswitch:1.2.0

**Comment by llollox** [comment]
Please...could you provide more details about your problem?

**Comment by nitiwatpolo** [comment]
me too.
try compile 'us.belka:androidtoggleswitch:1.1.1'

**Comment by paxdron** [comment]
try compile 'com.github.BelkaLab:Android-Toggle-Switch:c1b9ef587b'

**Comment by louistsaitszho** [comment]
i think 1.2.0 was never on
https://bintray.com/llollox/maven/Android-Toggle-Switch/view

**Comment by Lakshan-FG** [comment]
#11

**Comment by llollox** [comment]
Problem fixed! :)

Now you can use the feature on version 1.2.0!
Sorry for the delay!!
